site_name: FAST Project
site_description: Website of the FAST ANR project on Fast Audio Signal-processing Technologies on FPGA
copyright: Copyright &copy; 2020 <a href="http://www.grame.fr">Grame-CNCM</a>, <a href="http://www.citi-lab.fr/">CITI Lab</a> & <a href="http://lmfa.ec-lyon.fr/?lang=en">LMFA</a>
nav:
    - Overview : overview.md
    - Results :
         - 'Faust FPGA Audio Processor Prototype': results/processor.md
         - 'SyFaLa Tool-Chain': https://github.com/inria-emeraude/syfala
    - Jobs : jobs.md
    - Contacts : contacts.md
      
theme: 
  name: mkdocs
  custom_dir: 'theme'
  navigation_depth: 4
  
site_dir: ../docs

plugins:
  - search

extra:
  search:
    language: en
